# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: community
name: routeros
version: 0.2.0
readme: README.md
authors:
  - Egor Zaitsev (github.com/heuels)
  - Nikolay Dachev (github.com/NikolayDachev)
description: Modules for MikroTik RouterOS
license_file: COPYING
tags:
  - network
  - mikrotik
  - routeros
dependencies:
  ansible.netcommon: '>=1.0.0'
repository: https://github.com/ansible-collections/community.routeros
documentation: https://ansible.fontein.de/collections/community/routeros/
#documentation: https://github.com/ansible-collection-migration/community.routeros/tree/main/docs
homepage: https://github.com/ansible-collections/community.routeros
issues: https://github.com/ansible-collections/community.routeros/issues
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
