# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: community
name: routeros
version: 2.1.0
readme: README.md
authors:
  - Egor Zaitsev (github.com/heuels)
  - Nikolay Dachev (github.com/NikolayDachev)
  - Felix Fontein (github.com/felixfontein)
description: Modules for MikroTik RouterOS
license:
  - GPL-3.0-or-later
#license_file: COPYING
tags:
  - network
  - mikrotik
  - routeros
dependencies:
  ansible.netcommon: '>=1.0.0'
repository: https://github.com/ansible-collections/community.routeros
documentation: https://docs.ansible.com/ansible/devel/collections/community/routeros/
homepage: https://github.com/ansible-collections/community.routeros
issues: https://github.com/ansible-collections/community.routeros/issues
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
