---
minor_changes:
  - api_info, api_modify - add ``interface ethernet switch port-isolation`` which is supported since RouterOS 6.43 (https://github.com/ansible-collections/community.routeros/pull/375).
  - |
    api_info, api_modify - Add ``/routing bfd configuration``. Officially stabilized BFD support for BGP and OSPF is available since RouterOS 7.11
    See: https://iparchitechs.com/mikrotik-routeros-v7-11-stable-released/