---
minor_changes:
  - api_info, api_modify - Add ``/interface ethernet switch port-isolation`` which is supported since RouterOS 6.43
  - |
    api_info, api_modify - Add ``/routing bfd configuration``. Officially stabilized BFD support for BGP and OSPF is available since RouterOS 7.11
    See: https://iparchitechs.com/mikrotik-routeros-v7-11-stable-released/